#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

LOCAL=""
while getopts "l" arg
do
	case $arg in
            l) LOCAL="yes" ;;
        esac
done
ANON=`date`
print $ANON

git add README.md 
git add pushit
git add learn_dev.html
git add learn.js
git add plugins.js
git add bootstrap.css
git add build
git add jquery-1.12.4.min.js
git add jquery331min.js
git add jquery-ui-1.12.1.min.js
git add vjs.js



git add backtotop.css
git add FeedEk.js
git add learn_style.css
git add theme.css
git add video.css
git add con.png
git add hal.jpg



git commit -m "Update"

if [ "$LOCAL" == "" ] ; then
     git push -u origin master
fi

